# Copyright (C) 2024 Project-ACT
# 
# This file is part of ov-tessellation.
# 
# ov-tessellation is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ov-tessellation is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ov-tessellation.  If not, see <https://www.gnu.org/licenses/>.

title: "[External Bug]: Edit title after colon"
labels:
  - extbug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        # External Bug

        Please use this Discussion Category to describe an issue, problem, or defect
        you have encountered using one or more components of this Initiative.

        One Initiative is composed of several component projects and other moving parts,
        there is no reason you should need to dive in to the inner workings to report
        some finding… you are using GitHub, though, which means you are a bit closer to
        the structure and inner workings than most.

        Please take a moment to fill this in, your GitHub credentials will be used to
        attribute your contribution to this initiative unless you would rather opt out.

  - type: markdown
    attributes:
      value: "## Short Description"
        
  - type: textarea
    id: shortdesc
    attributes:
      label: Brief Summary Description of the Bug
      description: Augments the issue title with an extended description

    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Me as User"

  - type: checkboxes
    attributes:
      label: I am a…
      description: So we can consider some implementation specifics.
      options:
        - label: "**Organization Maintainer** responsible for a cohort of one or more people"
        - label: "**Organization Member** is anyone considered to be a part of an organization"
        - label: "**Project Maintainer** responsible for managing project(s)"
        - label: "**Project Contributor** a person who is part of an organization contributing to project(s)"
        - label: "**External Contributor** a person discovering projects"
        - label: "**Casual User** a curious person checking stuff out"
        - label: "**Automated User** a spider or other bot or similar"
        - label: "**Catalog Maintainer** oversees the gathered data from remote orgs and projects"
        - label: "**Spider Maintainer** oversees operation of the automation of gathering data from orgs and projects"
        - label: "**Visualization Maintainer** integrates graph visualizations into other platform(s)"
        - label: "**Notification Maintainer** manages integration of notifications with messaging tools and channels"
        - label: "**Tessellation Contributor** works on Tessellation components in any capacity"


  - type: markdown
    attributes:
      value: |
        ## Full Description

        As complete as possible, including what happened, what was expected to happen,


  - type: textarea
    id: description
    attributes:
      label: Full Bug Description
      description: Relevant configurations, inputs, outputs, what went wrong?
      placeholder: |
        Logs, screenshots, software, hardware, device details, versions, etc.

    validations:
      required: true


